mentors/urls.py
from django.urls import path, include
from mentors.views import reminder_view, get_group_view, mark_attendance_view, main_view

urlpatterns = [
    path('reminder/', reminder_view, name='m_reminder'),
    path('get_group/', get_group_view, name='get_group'),
    path('child_list/<int:group_number>/', mark_attendance_view, name='get_child'),
    path('', main_view)
]

mysad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('parents/', include('parents.urls')),
    path('mentors/', include('mentors.urls')),
    path('', include('start_page.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

parents/urls.py
from django.urls import path
from parents.views import main_view

urlpatterns = [
    path('', main_view, name='main'),
    ]

start_page/urls.py
from django.urls import path
from .views import landing

urlpatterns = [
    path('', landing)
]

mentors/models.py
from datetime import datetime
from django.db import models


class Mentor(models.Model):
    mentor_id = models.AutoField(primary_key=True)
    mentor_name = models.CharField(max_length=100)
    professional_grade = models.CharField(max_length=100)
    username = models.CharField(max_length=20, default=models.SET_NULL, null=True)
    password = models.CharField(max_length=20, default=models.SET_NULL, null=True)


class Group(models.Model):
    group_id = models.AutoField(primary_key=True)
    mentor_id = models.ForeignKey('Mentor', on_delete=models.CASCADE)
    grade = models.IntegerField()


class Reminders(models.Model):
    reminder_id = models.AutoField(primary_key=True)
    message = models.CharField(max_length=255)
    deadline = models.DateField()


class Attendance(models.Model):
    attendance_id = models.AutoField(primary_key=True)
    today_date = models.DateField(default=datetime.today)
    child = models.ForeignKey('Child', on_delete=models.CASCADE)
    is_arrived = models.BooleanField(default=False)
    group = models.ForeignKey('Group', on_delete=models.CASCADE, null=True)
    child_name = models.CharField(max_length=100, null=True)


class Child(models.Model):
    child_id = models.AutoField(primary_key=True)
    child_name = models.CharField(max_length=40)
    birth_date = models.DateField()
    group_id = models.ForeignKey('Group', on_delete=models.CASCADE)

parents/models.py
from django.db import models


class Schedule(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    start = models.TimeField()
    end = models.TimeField()
    grade = models.IntegerField(default=1)


class Family(models.Model):
    family_id = models.AutoField(primary_key=True)
    child_surname = models.CharField(max_length=20)
    mother_name = models.CharField(max_length=100)
    father_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

start_page/models.py
from django.db import models

# Create your models here.

mentors/forms.py
from django import forms
from .models import Reminders, Attendance, Group
from bootstrap_datepicker_plus.widgets import DatePickerInput
from datetime import datetime as dt
from django.forms import formset_factory


class ReminderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['message'].label = 'Сообщение'
        self.fields['deadline'].label = 'Срок напоминания'
    class Meta:
        model = Reminders
        fields = ['message', 'deadline']
        widgets = {
            'deadline': forms.SelectDateWidget(),
            'message': forms.Textarea(attrs={'cols': 30, 'rows': 10}),
        }


class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = ['is_arrived']

AttendanceFormFormSet = formset_factory(AttendanceForm, extra=0)

mentors/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from .forms import ReminderForm, AttendanceFormFormSet
from .models import *
import datetime as dt
from django.contrib.auth.decorators import login_required
from django.urls import reverse


def main_view(request):
    return render(request, 'mentors/main_page.html')


# Эта вьюшка для создания напоминаний воспитателями
@login_required
def reminder_view(request): 
    if request.method == 'POST':
        form = ReminderForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ReminderForm()
    return render(request, 'mentors/m_reminder_temp.html', {'form': form})


# На эту вьюшку перекидывает, чтобы проставить посещаемость с вьюшки "get_group"
@login_required
def mark_attendance_view(request, group_number):
    today = dt.date.today()
    children = Child.objects.filter(group_id_id=group_number)
    
    attendance_exists = Attendance.objects.filter(group_id=group_number, today_date=today).exists()
    if not attendance_exists:
        for child in children:
            Attendance.objects.create(
                child_id=child.child_id,
                group_id=group_number,
                child_name=child.child_name,
                today_date=today
            )

    children2 = Attendance.objects.filter(group_id=group_number, today_date=today)
    if request.method == 'POST':
        for child in children2:
            is_arrived = request.POST.get(str(child.attendance_id))
            child.is_arrived = is_arrived == 'on'
            child.save()

    return render(request, 'mentors/mark_attendance_temp.html', {'children': children2})



# На этой вьюшке ты выбираешь группу, по которой будешь выставлять посещаемость
@login_required
def get_group_view(request):
    group = Group.objects.values_list('group_id', flat=True)
    if request.method == 'POST':
        group_number = request.POST.get('group_number')
        return redirect(reverse('get_child', kwargs={'group_number': group_number}))
    return render(request, 'mentors/get_group_temp.html', {'group': group})

parents/views.py
from django.shortcuts import render
from .models import Schedule, Family
from datetime import datetime as dt
import pytz
from mentors.models import Reminders
from django.contrib.auth.decorators import login_required

mtz = pytz.timezone('Europe/Moscow')
now = dt.now(mtz)


@login_required
def main_view(request):
    schedule = Schedule.objects.filter(start__lt=now, end__gt=now).first()
    reminder = Reminders.objects.order_by('-deadline').first()
    family_surname = Family.objects.filter(family_id=1).first()
    return render(request, 'parents/main_temp.html', {'schedule': schedule, 'reminder': reminder, 'surname': family_surname})

start_page/views.py
from django.shortcuts import render


def landing(request):
    return render(request, 'start_page/base.html')

templates/base_generic.html
<!doctype html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
</head>

<body>
  {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
  {% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>

templates/mentors/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        .header-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
            width: 50%;
            margin: 0 auto;
        }

        .subheader_content {
            display: flex;
            justify-content: space-between;
            width: 50%;
        }

        .main-container {
            width: 50%;
            margin: 0 auto;
        }

        .first {
            padding-top: 10px;
            padding-bottom: 5px;
        }

        footer {
            color: white;
            background-color: black;
            position: fixed;
            right: 0;
            bottom: 0;
            text-align: center;
            width: 100%;
        }

        .child-info {
            display: flex;
            align-items: center;
        }

        .circle {
            width: 20px;
            height: 20px;
            background-color: red;
            border-radius: 50%;
            margin-right: 10px;
        }

        form {
            padding-top: 20px;
            width: 50%;
            margin: 0 auto;
        }

        form div {
            margin-bottom: 15px;
            position: relative;
        }

        label, span {
            display: block;
            margin-bottom: 5px;
        }

        textarea {
            border-width: 0;
            width: 100%;
            padding: 10px;
            background: #e6e6e6;
            border-radius: 5px;
        }

        input[type="date"] {
            border-width: 0;
            width: 100%;
            padding: 10px;
            background: #e6e6e6;
            border-radius: 5px;
        }

        button {
            margin-top: 20px;
            padding: 10px;
            border-width: 0;
            display: block;
            background: #4CAF50;
            color: white;
            text-transform: uppercase;
            border-radius: 5px;
        }

        select {
            padding: 5px;
            background: #e6e6e6;
            border-radius: 5px;
        }

    </style>
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <header>
        <div class="header-content">
            <h1>{% block header %}{% endblock header %}</h1>

            <div class="subheader_content">
                <p><a href="{% url 'm_reminder' %}">Напоминания</a></p>
                <p><a href="{% url 'get_group' %}">Посещаемость</a></p>
                <p><a href="/accounts/logout">Выйти</a></p>
            </div>
        </div>
    </header> 

    <main>
        {% block content %}
        Hello, Olga!
        {% endblock content %}
    </main>

    <footer>
        <p>Moi-sad@2024</p>
    </footer>

</body>

</html>

templates/mentors/get_group_temp.html
{% extends "mentors/base.html" %}
{% block title %}Выбор группы{% endblock title %}
{% block header %}Выберите группу{% endblock header %}
{% block content %}
<form method="post" id="groupForm" action="{% url 'get_group' %}">
    {% csrf_token %}
    <select name="group_number" id="id_group">
        {% for g in group %}
        <option value="{{g}}">{{g}}</option>
        {%endfor%}
    </select>
    <button type="submit" >Показать детей</button>
</form>

<!-- <script>
    function submitForm() {
        document.getElementById("groupForm").action = "{% url 'get_child' 0 %}".replace('0', document.getElementById("id_group").value);
        document.getElementById("groupForm").submit();
    }
</script> onclick="submitForm()" -->

{% endblock content %}

templates/mentors/m_reminder_temp.html
{% extends "mentors/base.html" %}
{% block title %}Напоминания{% endblock title %}
{% block header %}Уведомить{% endblock header %}
{% block content %}
<div class="main-container">
  <form action="{% url 'm_reminder' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Отправить</button>
  </form>
</div>

{% endblock content %}

templates/mentors/main_page.html
{% extends "mentors/base.html" %}
{% block title %}Личнный кабинет{% endblock title %}
{% block header %}Личный кабинет{% endblock header %}
{% block content %}
<p style="margin: 0 auto; width: 50%; padding-top: 15px;">Добро пожаловать в Мой Сад, Ольга!</p>

{% endblock content %}

templates/mentors/mark_attendance_temp.html
{% extends "mentors/base.html" %}
{% block title %}Посещаемость{% endblock title %}
{% block header %}Посещаемость{% endblock header %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <table style="margin: 20px auto; text-align: center;">
      <thead>
        <tr>
          <th style="font-size: large; padding-bottom: 10px;">Имя ребенка</th>
          <th style="font-size: large; padding-bottom: 10px;">Посещаемость</th>
        </tr>
      </thead>
      <tbody>
        {% for child in children %}
        <tr>
          <td style="text-align: left;">{{ child.child.child_name }}</td>
          <td>
            <label>
              <input type="checkbox" name="{{ child.attendance_id }}" {% if child.is_arrived %}checked{% endif %}>  
            </label>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <button type="submit" style="display: block; margin: 0 auto;">Отправить</button>
  </form>
{% endblock content %}

templates/parents/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        .header-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
            width: 50%;
            margin: 0 auto;
        }

        .main-container {
            width: 50%;
            margin: 0 auto;
        }

        .first {
            padding-top: 10px;
            padding-bottom: 5px;
        }

        footer {
            color: white;
            background-color: black;
            position: fixed;
            right: 0;
            bottom: 0;
            text-align: center;
            width: 100%;
        }

        .child-info {
            display: flex;
            align-items: center;
        }

        .circle {
            width: 20px;
            height: 20px;
            background-color: {% block color %}{% endblock color %};
            border-radius: 50%;
            margin-right: 10px;
        }
    </style>
    <title>Мой сад.Родители</title>
</head>

<body>
    <header>
        <div class="header-content">
            <div class="child-info">
                <div class="circle"></div>
                <h1>{% block child_surname %}{% endblock child_surname %}</h1>
            </div>
            <a href="/accounts/logout">Выйти</a>
        </div>
    </header> 

    <main>
        <div class="main-container">
            <div class="first">
                <h2>Сейчас:</h2>
                <p>{% block child_action %}{% endblock child_action %}</p>
            </div>
            <div>
                <h2>Напоминания:</h2>
                <p>{% block mentors_remidner %}{% endblock mentors_remidner %}</p>
            </div>
        </div>
    </main>

    <footer>
        <p>Moi-sad@2024</p>
    </footer>
</body>

</html>

templates/parents/main_temp.html
{% extends "parents/base.html" %}
{% block color %}red{% endblock color %}
{% block child_surname %}{{surname.child_surname}}{% endblock child_surname %}
{% block child_action %}{{schedule.name}}{% endblock child_action %}
{% block mentors_remidner %}{{reminder.message}} к {{reminder.deadline}}{% endblock mentors_remidner %}

templates/start_page/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            width: 50%;
            margin: auto;
        }
    </style>
    <title>Мой Сад</title>
</head>
<body>
    <h1>Мой Сад - это сервис для детских садов и воспитателей, приходите к нам и мы сделаем все по красоте!</h1>
    <a href="/parents">Я родитель</a>
    <br>
    <a href="/mentors">Я воспитатель</a>
</body>
</html>